### ISSUE TITLE
Is ther any immune cell signature matrix available ?

### ISSUE THREAD

**Issue by gudeqing** [tgac-vumc/BLADE#1]
Hi, is there any immune cell signature matrix available  for BLADE?

**Comment by anoyaro84** [comment]
Dear gudeqing,

Thanks for your interest to BLADE.
We do not provide signature matrix with BLADE.
There are several signatures publically available, but I would recommend you to create own signature using single-cell RNA-seq data from the relevant context.

**Comment by anoyaro84** [comment]
Dear qudeqing,

In the latest commit (742d1e8), I attached the signatures used in the publication.
That includes the followings:

- PBMC signatures (mean and standard deviation) for levels 1-4 classification of immune cell types
- PDAC signatures (mean and standard deviation)

I hope this is useful for you & others who wants to test BLADE quickly.
