### ISSUE TITLE
Time consumption for BLADE

### ISSUE THREAD

**Issue by poseidonchan** [tgac-vumc/BLADE#2]
hello:
I want to ask how long will BLADE take to produce a result with the default parameters? I want to deconvolve 500 bulk samples with 10000+ genes using a signature matrix (the mean matrix) from the corresponding single-cell profiles (5 cell types with 10000+ genes) and a variance matrix derived from the same profile. The number of processes is set to be 50, we run it on a workstation with 48 threads. The last time I tried to run it, it took me about 42 hours but no messages have been logged.  The **only** message is "_[Parallel(n_jobs=50)]: Using backend LockBackend with 50 concurrent workers_". Is it caused by the very large non-selected signature matrix? Can you help me solve this problem? Thanks in advance!

**Comment by anoyaro84** [comment]
Hi poseidonchan,

I am afraid that the computation time is not the strength of BLADE. As you can see from the Demo we provided & all experiments from the publication, we use ~1000+ genes for the deconvolution. I believe this would make a huge difference in computing time. What I can recommend is to cut the number of genes (for instance, by selecting only the top DEGs for deconvolution) and try this again. If you really need to use all of the 10,000 genes, then you should work with `BLADE` class object which has a functionality to run with a pre-determined cell type fraction. So you can give an estimated cell type fraction from the outcome with <1000 genes and let it just run the purification. I think this is feasible in terms of computing time.
Let me know if this is indeed your interest.


Kind regards,
Yongsoo

**Comment by poseidonchan** [comment]
Hi, anoyaro84:
Really thanks for your reply, I will select marker genes first and run again. I may bother you if I have other questions in the future.
